#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
#MISE description="Show version string"
set -euo pipefail

GIT_SHORT_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
VERSION="${VERSION:-dev-$GIT_SHORT_SHA}"
echo "$VERSION"
