// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"database/sql"
)

type Device struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	HostPath      string         `json:"host_path"`
	ContainerPath string         `json:"container_path"`
	Permissions   string         `json:"permissions"`
	Gid           int64          `json:"gid"`
	VmID          sql.NullString `json:"vm_id"`
	CreatedAt     string         `json:"created_at"`
}

type Drive struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	SizeBytes int64          `json:"size_bytes"`
	MountPath string         `json:"mount_path"`
	VmID      sql.NullString `json:"vm_id"`
	CreatedAt string         `json:"created_at"`
}

type Vm struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	Role            string         `json:"role"`
	Image           string         `json:"image"`
	Runtime         string         `json:"runtime"`
	State           string         `json:"state"`
	CreatedAt       string         `json:"created_at"`
	StartedAt       sql.NullString `json:"started_at"`
	StoppedAt       sql.NullString `json:"stopped_at"`
	Ip              string         `json:"ip"`
	Gateway         string         `json:"gateway"`
	NetnsPath       string         `json:"netns_path"`
	DnsServers      sql.NullString `json:"dns_servers"`
	DnsSearch       sql.NullString `json:"dns_search"`
	RootSize        int64          `json:"root_size"`
	RestartPolicy   string         `json:"restart_policy"`
	RestartStrategy string         `json:"restart_strategy"`
	Shell           string         `json:"shell"`
}
