// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlite

import (
	"context"
	"database/sql"
)

const countVMs = `-- name: CountVMs :one
SELECT COUNT(*) FROM vms
`

func (q *Queries) CountVMs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVMs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteVM = `-- name: DeleteVM :exec
DELETE FROM vms WHERE id = ?
`

func (q *Queries) DeleteVM(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteVM, id)
	return err
}

const getVM = `-- name: GetVM :one
SELECT id, name, role, image, runtime, state, created_at, started_at, stopped_at
FROM vms WHERE id = ?
`

func (q *Queries) GetVM(ctx context.Context, id string) (Vm, error) {
	row := q.db.QueryRowContext(ctx, getVM, id)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Image,
		&i.Runtime,
		&i.State,
		&i.CreatedAt,
		&i.StartedAt,
		&i.StoppedAt,
	)
	return i, err
}

const getVMByName = `-- name: GetVMByName :one
SELECT id, name, role, image, runtime, state, created_at, started_at, stopped_at
FROM vms WHERE name = ?
`

func (q *Queries) GetVMByName(ctx context.Context, name string) (Vm, error) {
	row := q.db.QueryRowContext(ctx, getVMByName, name)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Image,
		&i.Runtime,
		&i.State,
		&i.CreatedAt,
		&i.StartedAt,
		&i.StoppedAt,
	)
	return i, err
}

const insertVM = `-- name: InsertVM :exec

INSERT INTO vms (id, name, role, image, runtime, state, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertVMParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Role      string `json:"role"`
	Image     string `json:"image"`
	Runtime   string `json:"runtime"`
	State     string `json:"state"`
	CreatedAt string `json:"created_at"`
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) InsertVM(ctx context.Context, arg InsertVMParams) error {
	_, err := q.db.ExecContext(ctx, insertVM,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.Image,
		arg.Runtime,
		arg.State,
		arg.CreatedAt,
	)
	return err
}

const listVMs = `-- name: ListVMs :many
SELECT id, name, role, image, runtime, state, created_at, started_at, stopped_at
FROM vms ORDER BY created_at DESC
`

func (q *Queries) ListVMs(ctx context.Context) ([]Vm, error) {
	rows, err := q.db.QueryContext(ctx, listVMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vm{}
	for rows.Next() {
		var i Vm
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Image,
			&i.Runtime,
			&i.State,
			&i.CreatedAt,
			&i.StartedAt,
			&i.StoppedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVMsByRole = `-- name: ListVMsByRole :many
SELECT id, name, role, image, runtime, state, created_at, started_at, stopped_at
FROM vms WHERE role = ? ORDER BY created_at DESC
`

func (q *Queries) ListVMsByRole(ctx context.Context, role string) ([]Vm, error) {
	rows, err := q.db.QueryContext(ctx, listVMsByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vm{}
	for rows.Next() {
		var i Vm
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Image,
			&i.Runtime,
			&i.State,
			&i.CreatedAt,
			&i.StartedAt,
			&i.StoppedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVMStarted = `-- name: UpdateVMStarted :exec
UPDATE vms SET state = 'running', started_at = ? WHERE id = ?
`

type UpdateVMStartedParams struct {
	StartedAt sql.NullString `json:"started_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateVMStarted(ctx context.Context, arg UpdateVMStartedParams) error {
	_, err := q.db.ExecContext(ctx, updateVMStarted, arg.StartedAt, arg.ID)
	return err
}

const updateVMStateCreated = `-- name: UpdateVMStateCreated :exec
UPDATE vms SET state = 'created', started_at = NULL, stopped_at = NULL WHERE id = ?
`

func (q *Queries) UpdateVMStateCreated(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateVMStateCreated, id)
	return err
}

const updateVMStopped = `-- name: UpdateVMStopped :exec
UPDATE vms SET state = 'stopped', stopped_at = ? WHERE id = ?
`

type UpdateVMStoppedParams struct {
	StoppedAt sql.NullString `json:"stopped_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateVMStopped(ctx context.Context, arg UpdateVMStoppedParams) error {
	_, err := q.db.ExecContext(ctx, updateVMStopped, arg.StoppedAt, arg.ID)
	return err
}
