// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlite

import (
	"context"
	"database/sql"
)

const attachDevice = `-- name: AttachDevice :exec
UPDATE devices SET vm_id = ? WHERE id = ?
`

type AttachDeviceParams struct {
	VmID sql.NullString `json:"vm_id"`
	ID   string         `json:"id"`
}

func (q *Queries) AttachDevice(ctx context.Context, arg AttachDeviceParams) error {
	_, err := q.db.ExecContext(ctx, attachDevice, arg.VmID, arg.ID)
	return err
}

const attachDrive = `-- name: AttachDrive :exec
UPDATE drives SET vm_id = ? WHERE id = ?
`

type AttachDriveParams struct {
	VmID sql.NullString `json:"vm_id"`
	ID   string         `json:"id"`
}

func (q *Queries) AttachDrive(ctx context.Context, arg AttachDriveParams) error {
	_, err := q.db.ExecContext(ctx, attachDrive, arg.VmID, arg.ID)
	return err
}

const countTemplateRefs = `-- name: CountTemplateRefs :one
SELECT COUNT(*) FROM vms WHERE template_id = ? AND init = 1
`

func (q *Queries) CountTemplateRefs(ctx context.Context, templateID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTemplateRefs, templateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTemplates = `-- name: CountTemplates :one
SELECT COUNT(*) FROM templates
`

func (q *Queries) CountTemplates(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTemplates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVMs = `-- name: CountVMs :one
SELECT COUNT(*) FROM vms
`

func (q *Queries) CountVMs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVMs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = ?
`

func (q *Queries) DeleteDevice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, id)
	return err
}

const deleteDrive = `-- name: DeleteDrive :exec
DELETE FROM drives WHERE id = ?
`

func (q *Queries) DeleteDrive(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDrive, id)
	return err
}

const deleteSnapshotByID = `-- name: DeleteSnapshotByID :exec
DELETE FROM snapshots WHERE id = ?
`

func (q *Queries) DeleteSnapshotByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSnapshotByID, id)
	return err
}

const deleteTagsByVM = `-- name: DeleteTagsByVM :exec
DELETE FROM vm_tags WHERE vm_id = ?
`

func (q *Queries) DeleteTagsByVM(ctx context.Context, vmID string) error {
	_, err := q.db.ExecContext(ctx, deleteTagsByVM, vmID)
	return err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates WHERE id = ?
`

func (q *Queries) DeleteTemplate(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTemplate, id)
	return err
}

const deleteVM = `-- name: DeleteVM :exec
DELETE FROM vms WHERE id = ?
`

func (q *Queries) DeleteVM(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteVM, id)
	return err
}

const detachAllDevices = `-- name: DetachAllDevices :exec
UPDATE devices SET vm_id = NULL WHERE vm_id = ?
`

func (q *Queries) DetachAllDevices(ctx context.Context, vmID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, detachAllDevices, vmID)
	return err
}

const detachAllDrives = `-- name: DetachAllDrives :exec
UPDATE drives SET vm_id = NULL WHERE vm_id = ?
`

func (q *Queries) DetachAllDrives(ctx context.Context, vmID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, detachAllDrives, vmID)
	return err
}

const detachDevice = `-- name: DetachDevice :exec
UPDATE devices SET vm_id = NULL WHERE id = ?
`

func (q *Queries) DetachDevice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, detachDevice, id)
	return err
}

const detachDrive = `-- name: DetachDrive :exec
UPDATE drives SET vm_id = NULL WHERE id = ?
`

func (q *Queries) DetachDrive(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, detachDrive, id)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT id, name, host_path, container_path, permissions, gid, vm_id, created_at
FROM devices WHERE id = ?
`

func (q *Queries) GetDevice(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HostPath,
		&i.ContainerPath,
		&i.Permissions,
		&i.Gid,
		&i.VmID,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceByName = `-- name: GetDeviceByName :one
SELECT id, name, host_path, container_path, permissions, gid, vm_id, created_at
FROM devices WHERE name = ?
`

func (q *Queries) GetDeviceByName(ctx context.Context, name string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByName, name)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HostPath,
		&i.ContainerPath,
		&i.Permissions,
		&i.Gid,
		&i.VmID,
		&i.CreatedAt,
	)
	return i, err
}

const getDevicesByVM = `-- name: GetDevicesByVM :many
SELECT id, name, host_path, container_path, permissions, gid, vm_id, created_at
FROM devices WHERE vm_id = ? ORDER BY host_path
`

func (q *Queries) GetDevicesByVM(ctx context.Context, vmID sql.NullString) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, getDevicesByVM, vmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HostPath,
			&i.ContainerPath,
			&i.Permissions,
			&i.Gid,
			&i.VmID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDrive = `-- name: GetDrive :one
SELECT id, name, size_bytes, mount_path, vm_id, created_at
FROM drives WHERE id = ?
`

func (q *Queries) GetDrive(ctx context.Context, id string) (Drive, error) {
	row := q.db.QueryRowContext(ctx, getDrive, id)
	var i Drive
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SizeBytes,
		&i.MountPath,
		&i.VmID,
		&i.CreatedAt,
	)
	return i, err
}

const getDriveByName = `-- name: GetDriveByName :one
SELECT id, name, size_bytes, mount_path, vm_id, created_at
FROM drives WHERE name = ?
`

func (q *Queries) GetDriveByName(ctx context.Context, name string) (Drive, error) {
	row := q.db.QueryRowContext(ctx, getDriveByName, name)
	var i Drive
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SizeBytes,
		&i.MountPath,
		&i.VmID,
		&i.CreatedAt,
	)
	return i, err
}

const getDrivesByVM = `-- name: GetDrivesByVM :many
SELECT id, name, size_bytes, mount_path, vm_id, created_at
FROM drives WHERE vm_id = ? ORDER BY name
`

func (q *Queries) GetDrivesByVM(ctx context.Context, vmID sql.NullString) ([]Drive, error) {
	rows, err := q.db.QueryContext(ctx, getDrivesByVM, vmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Drive{}
	for rows.Next() {
		var i Drive
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SizeBytes,
			&i.MountPath,
			&i.VmID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSnapshot = `-- name: GetSnapshot :one
SELECT id, vm_id, name, created_at FROM snapshots WHERE id = ?
`

func (q *Queries) GetSnapshot(ctx context.Context, id string) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, getSnapshot, id)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.VmID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getSnapshotByName = `-- name: GetSnapshotByName :one
SELECT id, vm_id, name, created_at FROM snapshots WHERE vm_id = ? AND name = ?
`

type GetSnapshotByNameParams struct {
	VmID string `json:"vm_id"`
	Name string `json:"name"`
}

func (q *Queries) GetSnapshotByName(ctx context.Context, arg GetSnapshotByNameParams) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, getSnapshotByName, arg.VmID, arg.Name)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.VmID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getTagsByVM = `-- name: GetTagsByVM :many
SELECT tag FROM vm_tags WHERE vm_id = ? ORDER BY tag
`

func (q *Queries) GetTagsByVM(ctx context.Context, vmID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTagsByVM, vmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, name, distro, script, created_at, updated_at
FROM templates WHERE id = ?
`

func (q *Queries) GetTemplate(ctx context.Context, id string) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Distro,
		&i.Script,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByDistro = `-- name: GetTemplateByDistro :one
SELECT id, name, distro, script, created_at, updated_at
FROM templates WHERE distro = ?
`

func (q *Queries) GetTemplateByDistro(ctx context.Context, distro string) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplateByDistro, distro)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Distro,
		&i.Script,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByName = `-- name: GetTemplateByName :one
SELECT id, name, distro, script, created_at, updated_at
FROM templates WHERE name = ?
`

func (q *Queries) GetTemplateByName(ctx context.Context, name string) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplateByName, name)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Distro,
		&i.Script,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVM = `-- name: GetVM :one
SELECT id, name, image, runtime, state, created_at, started_at, stopped_at, ip, gateway, netns_path, dns_servers, dns_search, root_size, restart_policy, restart_strategy, shell, init, template_id, script_override, env
FROM vms WHERE id = ?
`

func (q *Queries) GetVM(ctx context.Context, id string) (Vm, error) {
	row := q.db.QueryRowContext(ctx, getVM, id)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.Runtime,
		&i.State,
		&i.CreatedAt,
		&i.StartedAt,
		&i.StoppedAt,
		&i.Ip,
		&i.Gateway,
		&i.NetnsPath,
		&i.DnsServers,
		&i.DnsSearch,
		&i.RootSize,
		&i.RestartPolicy,
		&i.RestartStrategy,
		&i.Shell,
		&i.Init,
		&i.TemplateID,
		&i.ScriptOverride,
		&i.Env,
	)
	return i, err
}

const getVMByName = `-- name: GetVMByName :one
SELECT id, name, image, runtime, state, created_at, started_at, stopped_at, ip, gateway, netns_path, dns_servers, dns_search, root_size, restart_policy, restart_strategy, shell, init, template_id, script_override, env
FROM vms WHERE name = ?
`

func (q *Queries) GetVMByName(ctx context.Context, name string) (Vm, error) {
	row := q.db.QueryRowContext(ctx, getVMByName, name)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.Runtime,
		&i.State,
		&i.CreatedAt,
		&i.StartedAt,
		&i.StoppedAt,
		&i.Ip,
		&i.Gateway,
		&i.NetnsPath,
		&i.DnsServers,
		&i.DnsSearch,
		&i.RootSize,
		&i.RestartPolicy,
		&i.RestartStrategy,
		&i.Shell,
		&i.Init,
		&i.TemplateID,
		&i.ScriptOverride,
		&i.Env,
	)
	return i, err
}

const insertDevice = `-- name: InsertDevice :exec
INSERT INTO devices (id, name, host_path, container_path, permissions, gid, vm_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDeviceParams struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	HostPath      string         `json:"host_path"`
	ContainerPath string         `json:"container_path"`
	Permissions   string         `json:"permissions"`
	Gid           int64          `json:"gid"`
	VmID          sql.NullString `json:"vm_id"`
	CreatedAt     string         `json:"created_at"`
}

func (q *Queries) InsertDevice(ctx context.Context, arg InsertDeviceParams) error {
	_, err := q.db.ExecContext(ctx, insertDevice,
		arg.ID,
		arg.Name,
		arg.HostPath,
		arg.ContainerPath,
		arg.Permissions,
		arg.Gid,
		arg.VmID,
		arg.CreatedAt,
	)
	return err
}

const insertDrive = `-- name: InsertDrive :exec
INSERT INTO drives (id, name, size_bytes, mount_path, vm_id, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertDriveParams struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	SizeBytes int64          `json:"size_bytes"`
	MountPath string         `json:"mount_path"`
	VmID      sql.NullString `json:"vm_id"`
	CreatedAt string         `json:"created_at"`
}

func (q *Queries) InsertDrive(ctx context.Context, arg InsertDriveParams) error {
	_, err := q.db.ExecContext(ctx, insertDrive,
		arg.ID,
		arg.Name,
		arg.SizeBytes,
		arg.MountPath,
		arg.VmID,
		arg.CreatedAt,
	)
	return err
}

const insertSnapshot = `-- name: InsertSnapshot :exec
INSERT INTO snapshots (id, vm_id, name, created_at) VALUES (?, ?, ?, ?)
`

type InsertSnapshotParams struct {
	ID        string `json:"id"`
	VmID      string `json:"vm_id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, insertSnapshot,
		arg.ID,
		arg.VmID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const insertTag = `-- name: InsertTag :exec
INSERT OR IGNORE INTO vm_tags (vm_id, tag) VALUES (?, ?)
`

type InsertTagParams struct {
	VmID string `json:"vm_id"`
	Tag  string `json:"tag"`
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) error {
	_, err := q.db.ExecContext(ctx, insertTag, arg.VmID, arg.Tag)
	return err
}

const insertTemplate = `-- name: InsertTemplate :exec

INSERT INTO templates (id, name, distro, script, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertTemplateParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Distro    string `json:"distro"`
	Script    string `json:"script"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// Template queries
func (q *Queries) InsertTemplate(ctx context.Context, arg InsertTemplateParams) error {
	_, err := q.db.ExecContext(ctx, insertTemplate,
		arg.ID,
		arg.Name,
		arg.Distro,
		arg.Script,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertVM = `-- name: InsertVM :exec

INSERT INTO vms (id, name, image, runtime, state, created_at, ip, gateway, netns_path, dns_servers, dns_search, root_size, restart_policy, restart_strategy, shell, init, template_id, script_override, env)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertVMParams struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	Image           string         `json:"image"`
	Runtime         string         `json:"runtime"`
	State           string         `json:"state"`
	CreatedAt       string         `json:"created_at"`
	Ip              string         `json:"ip"`
	Gateway         string         `json:"gateway"`
	NetnsPath       string         `json:"netns_path"`
	DnsServers      sql.NullString `json:"dns_servers"`
	DnsSearch       sql.NullString `json:"dns_search"`
	RootSize        int64          `json:"root_size"`
	RestartPolicy   string         `json:"restart_policy"`
	RestartStrategy string         `json:"restart_strategy"`
	Shell           string         `json:"shell"`
	Init            int64          `json:"init"`
	TemplateID      sql.NullString `json:"template_id"`
	ScriptOverride  sql.NullString `json:"script_override"`
	Env             string         `json:"env"`
}

// SPDX-License-Identifier: GPL-3.0-or-later
func (q *Queries) InsertVM(ctx context.Context, arg InsertVMParams) error {
	_, err := q.db.ExecContext(ctx, insertVM,
		arg.ID,
		arg.Name,
		arg.Image,
		arg.Runtime,
		arg.State,
		arg.CreatedAt,
		arg.Ip,
		arg.Gateway,
		arg.NetnsPath,
		arg.DnsServers,
		arg.DnsSearch,
		arg.RootSize,
		arg.RestartPolicy,
		arg.RestartStrategy,
		arg.Shell,
		arg.Init,
		arg.TemplateID,
		arg.ScriptOverride,
		arg.Env,
	)
	return err
}

const listDevices = `-- name: ListDevices :many
SELECT id, name, host_path, container_path, permissions, gid, vm_id, created_at
FROM devices ORDER BY created_at DESC
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HostPath,
			&i.ContainerPath,
			&i.Permissions,
			&i.Gid,
			&i.VmID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDrives = `-- name: ListDrives :many
SELECT id, name, size_bytes, mount_path, vm_id, created_at
FROM drives ORDER BY created_at DESC
`

func (q *Queries) ListDrives(ctx context.Context) ([]Drive, error) {
	rows, err := q.db.QueryContext(ctx, listDrives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Drive{}
	for rows.Next() {
		var i Drive
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SizeBytes,
			&i.MountPath,
			&i.VmID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsByVM = `-- name: ListSnapshotsByVM :many
SELECT id, vm_id, name, created_at FROM snapshots WHERE vm_id = ? ORDER BY created_at
`

func (q *Queries) ListSnapshotsByVM(ctx context.Context, vmID string) ([]Snapshot, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotsByVM, vmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snapshot{}
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.VmID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, distro, script, created_at, updated_at
FROM templates ORDER BY name
`

func (q *Queries) ListTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Distro,
			&i.Script,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVMs = `-- name: ListVMs :many
SELECT id, name, image, runtime, state, created_at, started_at, stopped_at, ip, gateway, netns_path, dns_servers, dns_search, root_size, restart_policy, restart_strategy, shell, init, template_id, script_override, env
FROM vms ORDER BY created_at DESC
`

func (q *Queries) ListVMs(ctx context.Context) ([]Vm, error) {
	rows, err := q.db.QueryContext(ctx, listVMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vm{}
	for rows.Next() {
		var i Vm
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.Runtime,
			&i.State,
			&i.CreatedAt,
			&i.StartedAt,
			&i.StoppedAt,
			&i.Ip,
			&i.Gateway,
			&i.NetnsPath,
			&i.DnsServers,
			&i.DnsSearch,
			&i.RootSize,
			&i.RestartPolicy,
			&i.RestartStrategy,
			&i.Shell,
			&i.Init,
			&i.TemplateID,
			&i.ScriptOverride,
			&i.Env,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveDevice = `-- name: ResolveDevice :one
SELECT id, name, host_path, container_path, permissions, gid, vm_id, created_at
FROM devices WHERE id = ? OR name = ?
`

type ResolveDeviceParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ResolveDevice(ctx context.Context, arg ResolveDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, resolveDevice, arg.ID, arg.Name)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HostPath,
		&i.ContainerPath,
		&i.Permissions,
		&i.Gid,
		&i.VmID,
		&i.CreatedAt,
	)
	return i, err
}

const resolveDrive = `-- name: ResolveDrive :one
SELECT id, name, size_bytes, mount_path, vm_id, created_at
FROM drives WHERE id = ? OR name = ?
`

type ResolveDriveParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ResolveDrive(ctx context.Context, arg ResolveDriveParams) (Drive, error) {
	row := q.db.QueryRowContext(ctx, resolveDrive, arg.ID, arg.Name)
	var i Drive
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SizeBytes,
		&i.MountPath,
		&i.VmID,
		&i.CreatedAt,
	)
	return i, err
}

const resolveTemplate = `-- name: ResolveTemplate :one
SELECT id, name, distro, script, created_at, updated_at
FROM templates WHERE id = ? OR name = ?
`

type ResolveTemplateParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ResolveTemplate(ctx context.Context, arg ResolveTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, resolveTemplate, arg.ID, arg.Name)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Distro,
		&i.Script,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveVM = `-- name: ResolveVM :one
SELECT id, name, image, runtime, state, created_at, started_at, stopped_at, ip, gateway, netns_path, dns_servers, dns_search, root_size, restart_policy, restart_strategy, shell, init, template_id, script_override, env
FROM vms WHERE id = ? OR name = ?
`

type ResolveVMParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ResolveVM(ctx context.Context, arg ResolveVMParams) (Vm, error) {
	row := q.db.QueryRowContext(ctx, resolveVM, arg.ID, arg.Name)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.Runtime,
		&i.State,
		&i.CreatedAt,
		&i.StartedAt,
		&i.StoppedAt,
		&i.Ip,
		&i.Gateway,
		&i.NetnsPath,
		&i.DnsServers,
		&i.DnsSearch,
		&i.RootSize,
		&i.RestartPolicy,
		&i.RestartStrategy,
		&i.Shell,
		&i.Init,
		&i.TemplateID,
		&i.ScriptOverride,
		&i.Env,
	)
	return i, err
}

const updateTemplate = `-- name: UpdateTemplate :exec
UPDATE templates SET name = ?, distro = ?, script = ?, updated_at = ? WHERE id = ?
`

type UpdateTemplateParams struct {
	Name      string `json:"name"`
	Distro    string `json:"distro"`
	Script    string `json:"script"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error {
	_, err := q.db.ExecContext(ctx, updateTemplate,
		arg.Name,
		arg.Distro,
		arg.Script,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateVMEnv = `-- name: UpdateVMEnv :exec
UPDATE vms SET env = ? WHERE id = ?
`

type UpdateVMEnvParams struct {
	Env string `json:"env"`
	ID  string `json:"id"`
}

func (q *Queries) UpdateVMEnv(ctx context.Context, arg UpdateVMEnvParams) error {
	_, err := q.db.ExecContext(ctx, updateVMEnv, arg.Env, arg.ID)
	return err
}

const updateVMImage = `-- name: UpdateVMImage :exec
UPDATE vms SET image = ? WHERE id = ?
`

type UpdateVMImageParams struct {
	Image string `json:"image"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateVMImage(ctx context.Context, arg UpdateVMImageParams) error {
	_, err := q.db.ExecContext(ctx, updateVMImage, arg.Image, arg.ID)
	return err
}

const updateVMInit = `-- name: UpdateVMInit :exec
UPDATE vms SET init = ?, template_id = ?, script_override = ? WHERE id = ?
`

type UpdateVMInitParams struct {
	Init           int64          `json:"init"`
	TemplateID     sql.NullString `json:"template_id"`
	ScriptOverride sql.NullString `json:"script_override"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateVMInit(ctx context.Context, arg UpdateVMInitParams) error {
	_, err := q.db.ExecContext(ctx, updateVMInit,
		arg.Init,
		arg.TemplateID,
		arg.ScriptOverride,
		arg.ID,
	)
	return err
}

const updateVMNetwork = `-- name: UpdateVMNetwork :exec
UPDATE vms SET ip = ?, gateway = ?, netns_path = ? WHERE id = ?
`

type UpdateVMNetworkParams struct {
	Ip        string `json:"ip"`
	Gateway   string `json:"gateway"`
	NetnsPath string `json:"netns_path"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateVMNetwork(ctx context.Context, arg UpdateVMNetworkParams) error {
	_, err := q.db.ExecContext(ctx, updateVMNetwork,
		arg.Ip,
		arg.Gateway,
		arg.NetnsPath,
		arg.ID,
	)
	return err
}

const updateVMRestartPolicy = `-- name: UpdateVMRestartPolicy :exec
UPDATE vms SET restart_policy = ?, restart_strategy = ? WHERE id = ?
`

type UpdateVMRestartPolicyParams struct {
	RestartPolicy   string `json:"restart_policy"`
	RestartStrategy string `json:"restart_strategy"`
	ID              string `json:"id"`
}

func (q *Queries) UpdateVMRestartPolicy(ctx context.Context, arg UpdateVMRestartPolicyParams) error {
	_, err := q.db.ExecContext(ctx, updateVMRestartPolicy, arg.RestartPolicy, arg.RestartStrategy, arg.ID)
	return err
}

const updateVMRootSize = `-- name: UpdateVMRootSize :exec
UPDATE vms SET root_size = ? WHERE id = ?
`

type UpdateVMRootSizeParams struct {
	RootSize int64  `json:"root_size"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateVMRootSize(ctx context.Context, arg UpdateVMRootSizeParams) error {
	_, err := q.db.ExecContext(ctx, updateVMRootSize, arg.RootSize, arg.ID)
	return err
}

const updateVMShell = `-- name: UpdateVMShell :exec
UPDATE vms SET shell = ? WHERE id = ?
`

type UpdateVMShellParams struct {
	Shell string `json:"shell"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateVMShell(ctx context.Context, arg UpdateVMShellParams) error {
	_, err := q.db.ExecContext(ctx, updateVMShell, arg.Shell, arg.ID)
	return err
}

const updateVMStarted = `-- name: UpdateVMStarted :exec
UPDATE vms SET state = 'running', started_at = ? WHERE id = ?
`

type UpdateVMStartedParams struct {
	StartedAt sql.NullString `json:"started_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateVMStarted(ctx context.Context, arg UpdateVMStartedParams) error {
	_, err := q.db.ExecContext(ctx, updateVMStarted, arg.StartedAt, arg.ID)
	return err
}

const updateVMStateCreated = `-- name: UpdateVMStateCreated :exec
UPDATE vms SET state = 'created', started_at = NULL, stopped_at = NULL WHERE id = ?
`

func (q *Queries) UpdateVMStateCreated(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateVMStateCreated, id)
	return err
}

const updateVMStopped = `-- name: UpdateVMStopped :exec
UPDATE vms SET state = 'stopped', stopped_at = ? WHERE id = ?
`

type UpdateVMStoppedParams struct {
	StoppedAt sql.NullString `json:"stopped_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateVMStopped(ctx context.Context, arg UpdateVMStoppedParams) error {
	_, err := q.db.ExecContext(ctx, updateVMStopped, arg.StoppedAt, arg.ID)
	return err
}
