// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlite

import (
	"context"
	"database/sql"
)

const attachDevice = `-- name: AttachDevice :exec
UPDATE devices SET vm_id = ? WHERE id = ?
`

type AttachDeviceParams struct {
	VmID sql.NullString `json:"vm_id"`
	ID   string         `json:"id"`
}

func (q *Queries) AttachDevice(ctx context.Context, arg AttachDeviceParams) error {
	_, err := q.db.ExecContext(ctx, attachDevice, arg.VmID, arg.ID)
	return err
}

const attachDrive = `-- name: AttachDrive :exec
UPDATE drives SET vm_id = ? WHERE id = ?
`

type AttachDriveParams struct {
	VmID sql.NullString `json:"vm_id"`
	ID   string         `json:"id"`
}

func (q *Queries) AttachDrive(ctx context.Context, arg AttachDriveParams) error {
	_, err := q.db.ExecContext(ctx, attachDrive, arg.VmID, arg.ID)
	return err
}

const countVMs = `-- name: CountVMs :one
SELECT COUNT(*) FROM vms
`

func (q *Queries) CountVMs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVMs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = ?
`

func (q *Queries) DeleteDevice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, id)
	return err
}

const deleteDrive = `-- name: DeleteDrive :exec
DELETE FROM drives WHERE id = ?
`

func (q *Queries) DeleteDrive(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDrive, id)
	return err
}

const deleteVM = `-- name: DeleteVM :exec
DELETE FROM vms WHERE id = ?
`

func (q *Queries) DeleteVM(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteVM, id)
	return err
}

const detachAllDevices = `-- name: DetachAllDevices :exec
UPDATE devices SET vm_id = NULL WHERE vm_id = ?
`

func (q *Queries) DetachAllDevices(ctx context.Context, vmID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, detachAllDevices, vmID)
	return err
}

const detachAllDrives = `-- name: DetachAllDrives :exec
UPDATE drives SET vm_id = NULL WHERE vm_id = ?
`

func (q *Queries) DetachAllDrives(ctx context.Context, vmID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, detachAllDrives, vmID)
	return err
}

const detachDevice = `-- name: DetachDevice :exec
UPDATE devices SET vm_id = NULL WHERE id = ?
`

func (q *Queries) DetachDevice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, detachDevice, id)
	return err
}

const detachDrive = `-- name: DetachDrive :exec
UPDATE drives SET vm_id = NULL WHERE id = ?
`

func (q *Queries) DetachDrive(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, detachDrive, id)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT id, host_path, container_path, permissions, gid, vm_id, created_at
FROM devices WHERE id = ?
`

func (q *Queries) GetDevice(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.HostPath,
		&i.ContainerPath,
		&i.Permissions,
		&i.Gid,
		&i.VmID,
		&i.CreatedAt,
	)
	return i, err
}

const getDevicesByVM = `-- name: GetDevicesByVM :many
SELECT id, host_path, container_path, permissions, gid, vm_id, created_at
FROM devices WHERE vm_id = ? ORDER BY host_path
`

func (q *Queries) GetDevicesByVM(ctx context.Context, vmID sql.NullString) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, getDevicesByVM, vmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.HostPath,
			&i.ContainerPath,
			&i.Permissions,
			&i.Gid,
			&i.VmID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDrive = `-- name: GetDrive :one
SELECT id, name, size_bytes, mount_path, vm_id, created_at
FROM drives WHERE id = ?
`

func (q *Queries) GetDrive(ctx context.Context, id string) (Drive, error) {
	row := q.db.QueryRowContext(ctx, getDrive, id)
	var i Drive
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SizeBytes,
		&i.MountPath,
		&i.VmID,
		&i.CreatedAt,
	)
	return i, err
}

const getDriveByName = `-- name: GetDriveByName :one
SELECT id, name, size_bytes, mount_path, vm_id, created_at
FROM drives WHERE name = ?
`

func (q *Queries) GetDriveByName(ctx context.Context, name string) (Drive, error) {
	row := q.db.QueryRowContext(ctx, getDriveByName, name)
	var i Drive
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SizeBytes,
		&i.MountPath,
		&i.VmID,
		&i.CreatedAt,
	)
	return i, err
}

const getDrivesByVM = `-- name: GetDrivesByVM :many
SELECT id, name, size_bytes, mount_path, vm_id, created_at
FROM drives WHERE vm_id = ? ORDER BY name
`

func (q *Queries) GetDrivesByVM(ctx context.Context, vmID sql.NullString) ([]Drive, error) {
	rows, err := q.db.QueryContext(ctx, getDrivesByVM, vmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Drive{}
	for rows.Next() {
		var i Drive
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SizeBytes,
			&i.MountPath,
			&i.VmID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVM = `-- name: GetVM :one
SELECT id, name, role, image, runtime, state, created_at, started_at, stopped_at, ip, gateway, netns_path
FROM vms WHERE id = ?
`

func (q *Queries) GetVM(ctx context.Context, id string) (Vm, error) {
	row := q.db.QueryRowContext(ctx, getVM, id)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Image,
		&i.Runtime,
		&i.State,
		&i.CreatedAt,
		&i.StartedAt,
		&i.StoppedAt,
		&i.Ip,
		&i.Gateway,
		&i.NetnsPath,
	)
	return i, err
}

const getVMByName = `-- name: GetVMByName :one
SELECT id, name, role, image, runtime, state, created_at, started_at, stopped_at, ip, gateway, netns_path
FROM vms WHERE name = ?
`

func (q *Queries) GetVMByName(ctx context.Context, name string) (Vm, error) {
	row := q.db.QueryRowContext(ctx, getVMByName, name)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Image,
		&i.Runtime,
		&i.State,
		&i.CreatedAt,
		&i.StartedAt,
		&i.StoppedAt,
		&i.Ip,
		&i.Gateway,
		&i.NetnsPath,
	)
	return i, err
}

const insertDevice = `-- name: InsertDevice :exec
INSERT INTO devices (id, host_path, container_path, permissions, gid, vm_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertDeviceParams struct {
	ID            string         `json:"id"`
	HostPath      string         `json:"host_path"`
	ContainerPath string         `json:"container_path"`
	Permissions   string         `json:"permissions"`
	Gid           int64          `json:"gid"`
	VmID          sql.NullString `json:"vm_id"`
	CreatedAt     string         `json:"created_at"`
}

func (q *Queries) InsertDevice(ctx context.Context, arg InsertDeviceParams) error {
	_, err := q.db.ExecContext(ctx, insertDevice,
		arg.ID,
		arg.HostPath,
		arg.ContainerPath,
		arg.Permissions,
		arg.Gid,
		arg.VmID,
		arg.CreatedAt,
	)
	return err
}

const insertDrive = `-- name: InsertDrive :exec
INSERT INTO drives (id, name, size_bytes, mount_path, vm_id, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertDriveParams struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	SizeBytes int64          `json:"size_bytes"`
	MountPath string         `json:"mount_path"`
	VmID      sql.NullString `json:"vm_id"`
	CreatedAt string         `json:"created_at"`
}

func (q *Queries) InsertDrive(ctx context.Context, arg InsertDriveParams) error {
	_, err := q.db.ExecContext(ctx, insertDrive,
		arg.ID,
		arg.Name,
		arg.SizeBytes,
		arg.MountPath,
		arg.VmID,
		arg.CreatedAt,
	)
	return err
}

const insertVM = `-- name: InsertVM :exec

INSERT INTO vms (id, name, role, image, runtime, state, created_at, ip, gateway, netns_path)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertVMParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Role      string `json:"role"`
	Image     string `json:"image"`
	Runtime   string `json:"runtime"`
	State     string `json:"state"`
	CreatedAt string `json:"created_at"`
	Ip        string `json:"ip"`
	Gateway   string `json:"gateway"`
	NetnsPath string `json:"netns_path"`
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) InsertVM(ctx context.Context, arg InsertVMParams) error {
	_, err := q.db.ExecContext(ctx, insertVM,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.Image,
		arg.Runtime,
		arg.State,
		arg.CreatedAt,
		arg.Ip,
		arg.Gateway,
		arg.NetnsPath,
	)
	return err
}

const listDevices = `-- name: ListDevices :many
SELECT id, host_path, container_path, permissions, gid, vm_id, created_at
FROM devices ORDER BY created_at DESC
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.HostPath,
			&i.ContainerPath,
			&i.Permissions,
			&i.Gid,
			&i.VmID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDrives = `-- name: ListDrives :many
SELECT id, name, size_bytes, mount_path, vm_id, created_at
FROM drives ORDER BY created_at DESC
`

func (q *Queries) ListDrives(ctx context.Context) ([]Drive, error) {
	rows, err := q.db.QueryContext(ctx, listDrives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Drive{}
	for rows.Next() {
		var i Drive
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SizeBytes,
			&i.MountPath,
			&i.VmID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVMs = `-- name: ListVMs :many
SELECT id, name, role, image, runtime, state, created_at, started_at, stopped_at, ip, gateway, netns_path
FROM vms ORDER BY created_at DESC
`

func (q *Queries) ListVMs(ctx context.Context) ([]Vm, error) {
	rows, err := q.db.QueryContext(ctx, listVMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vm{}
	for rows.Next() {
		var i Vm
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Image,
			&i.Runtime,
			&i.State,
			&i.CreatedAt,
			&i.StartedAt,
			&i.StoppedAt,
			&i.Ip,
			&i.Gateway,
			&i.NetnsPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVMsByRole = `-- name: ListVMsByRole :many
SELECT id, name, role, image, runtime, state, created_at, started_at, stopped_at, ip, gateway, netns_path
FROM vms WHERE role = ? ORDER BY created_at DESC
`

func (q *Queries) ListVMsByRole(ctx context.Context, role string) ([]Vm, error) {
	rows, err := q.db.QueryContext(ctx, listVMsByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vm{}
	for rows.Next() {
		var i Vm
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Image,
			&i.Runtime,
			&i.State,
			&i.CreatedAt,
			&i.StartedAt,
			&i.StoppedAt,
			&i.Ip,
			&i.Gateway,
			&i.NetnsPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVMStarted = `-- name: UpdateVMStarted :exec
UPDATE vms SET state = 'running', started_at = ? WHERE id = ?
`

type UpdateVMStartedParams struct {
	StartedAt sql.NullString `json:"started_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateVMStarted(ctx context.Context, arg UpdateVMStartedParams) error {
	_, err := q.db.ExecContext(ctx, updateVMStarted, arg.StartedAt, arg.ID)
	return err
}

const updateVMStateCreated = `-- name: UpdateVMStateCreated :exec
UPDATE vms SET state = 'created', started_at = NULL, stopped_at = NULL WHERE id = ?
`

func (q *Queries) UpdateVMStateCreated(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateVMStateCreated, id)
	return err
}

const updateVMStopped = `-- name: UpdateVMStopped :exec
UPDATE vms SET state = 'stopped', stopped_at = ? WHERE id = ?
`

type UpdateVMStoppedParams struct {
	StoppedAt sql.NullString `json:"stopped_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateVMStopped(ctx context.Context, arg UpdateVMStoppedParams) error {
	_, err := q.db.ExecContext(ctx, updateVMStopped, arg.StoppedAt, arg.ID)
	return err
}
